### ISSUE TITLE
New feat prerequisites layout

### ISSUE THREAD

**Issue by jcte02** [openlegend/core-rules#278]
@brianfeister @ucffool I suggest we move the discussion here so it is easier to track.

So far we have introduced the keys `all` and `any`, which represent the query type that ties the child elements.
I would add support for nested `all` and `any` keys, so that the system really becomes flexible (and hopefully we don't have to reiterate it).
*e.g.* `Feat1 OR (Attribute1 AND Attribute2)`

````yaml
tierX:
  any:
    Feat:
    - Feat1
    all:
      Attribute:
      - Attribute1
      - Attribute2
````
~It is still implied an `or` query within the same `Feat` or `Attribute` tag.~ (this makes no sense, I was confused)

**Comment by brianfeister** [comment]
your example throws me off a bit:

```
tierX:
  any:
    Feat:
    - Feat1
    all:
      Attribute:
      - Attribute1
      - Attribute2
```

shouldn't that be

```
tierX:
  any:
    Feat:
    - Feat1
    all:
      Attribute:
      - Attribute1
      - Attribute2
     Feat:
     - Feat 1
     - Feat 2
```

Or are you demonstrating cascading `all` rules here?

Does your example require `Feat 1 || (Attribute1 && Attribute2)` or does it it require `Feat1 || Attribute1 || Attribute2`?

**Comment by jcte02** [comment]
@brianfeister  The example was for `Feat 1 || (Attribute1 && Attribute2)`.

**Comment by jcte02** [comment]
This is still a bit confusing, we need to work on it.

**Comment by ucffool** [comment]
I read it as `Feat 1 || (Attribute1 && Attribute2)`.

I read yours as `Feat 1 || (Attribute1 && Attribute2 && Feat 1 && Feat 2)`.

I'm thinking about the parsing and it seems consistency is important and key conflicts are still possible. Examples:

```
tierX:
  any:
    all:
      Feat:
      - Feat1
    all:
      Attribute:
      - Attribute1
      - Attribute2
```
Thus the logic shouldn't be a key but an attribute. I realize this makes it more programmer and less user-friendly, but it's consistent that the grouping isn't *sometimes* there.

```
tierX:
  groupby: any
    Feat:
    groupby: all
    - Feat1
    Attribute:
    groupby: all
    - Attribute1
    - Attribute2
```
I know above is not perfect and **not the answer**, but I'm trying to make the point.

**Comment by jcte02** [comment]
@ucffool Yes I was thinking the same. 
We need to specify the query top level and also inside the `Feat` and `Attribute` key.
Your example becomes:
````yaml
tierX:
  any:
    Feat:
     all:
     - Feat1
    Attribute:
      all:
      - Attribute1
      - Attribute2
````
With this approach I think key conflicts should be more rare.

**Comment by ucffool** [comment]
I wish I could `view source` on your comment so I knew how you got the color-coding.

**Comment by brianfeister** [comment]
It's achieved with ` ```yaml ` in the opening block

**Comment by jcte02** [comment]
@ucffool Yes sometimes markdown is a pain. You need a block of code, which is structurated like this
> '''language
code
'''

Subsitute the apostrophe for a backtid and languare the coding language.
You can find a Github Markdown cheatsheet [here](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

**Comment by ucffool** [comment]
I know markdown, and some of GitHub specifics, just didn't know about the language thing (or my eyes scanned past it every time I've been to that page). Anyway... back to our regularly scheduled conversation.

**Comment by jcte02** [comment]
With some regex magic I updated the feat prerequisite layout. 
[Here](https://github.com/openlegend/core-rules/compare/master...jcte02:new-feat-layout) you can view the diff with the `master` branch.

**Suggestions:**

1.
```yaml
Other:
- None
```
to
 ```yaml
Other: None
```
Since it is only a single string.

2.
```yaml
Attribute:
- Attribute1: Score1
- Attribute2: Score2
```
to
```yaml
Attribute:
  Attribute1: Score1
  Attribute2: Score2
```
Essentialy from an array of single hashes to a single hash (easier to iterate on application-wise).
Comparing the JSON outputs:
```json
{
  "Attribute": [
    {
      "Attribute1": "Score1"
    },
    {
      "Attribute2": "Score2"
    }
  ]
}
```
to
```json
{
  "Attribute": {
    "Attribute2": "Score2",
    "Attribute1": "Score1"
  }
}
```
