### ISSUE TITLE
Confusing Prerequisite (Energy Resistance)

### ISSUE THREAD

**Issue by Hassurunous** [openlegend/core-rules#82]
From the Feat list: 

Energy Resistance
Prerequisites:
>  Energy OR 4 / 5 / 7

"Energy OR 4/5/7" what?

I'm making a database of the feats, banes, and boons for my group because they are having trouble going through the list on the website. The sort and search features don't appear to be working properly on the website. I'm sure you guys have seen the issue before, and you're working on it. If there's anything I can do to help, let me know!

EDIT: It also appears that Tier 1 and Tier 2 are identical. Are you intended to choose a second type of damage? Or should the defense go up from 5? Just a bit confusing.

**Comment by brianfeister** [comment]
@Hassurunous are you a JavaScript developer? Angular JS? We could consider bringing you into the inner circle to work on the website code itself.

**Comment by Hassurunous** [comment]
I've done quite a bit of work with Javascript, and I'd be happy to learn Angular (I've been meaning to for a while now anyways). I'm also a student at Make School in San Francisco and the same Hassurunous that streamed Open Legend this past Sunday, so I'd love to help!

**Comment by brianfeister** [comment]
The code for feats is here:
https://github.com/brianfeister/open-legend-app/tree/master/client/src/app/feats

But before the filtering you're looking for can be made to work, all of the `feats.yml` need their `prerequisite` field updated to match the format of this gist:

https://gist.github.com/brianfeister/3d5ccc202b566ca06ece00b984662591

The basic idea is that the `prerequisite` property needs to contain an array of `tier{x}`'s. Rather than grouping everything together as plaintext (what I'm doing now), each tier needs to have it's own array of pre-requisites that must be met. Once you get all of that squared away (and for all I know @jean1880 has already finished this work) we can take the next step, which is to modify the template and controller code for (https://github.com/brianfeister/open-legend-app/tree/master/client/src/app/feats) the feats section so that pre-requisites from the new array of tiers are represented in a reasonable looking way in the UI.

```
- !
  name: Alternate Form (I - III)
  prerequisite:
  - tier1:
    - Attribute: 
      - Alteration: 2
    - Feat:
      - Some Other Feat Name
  - tier2:
    - Attribute:
      - Alteration: 5 
  - tier3:
    - Attribute:
      - Alteration: 7
    - Feat:
      - Another Feat Name
  tags:
  - Supernatural
  cost:
  - 3
  description: |
    Alternate form is an ability possessed by lyncanthropes (werewolves, werebears, wererats), druids, vampires, and other creatures capable of assuming <emphasis>specific</emphasis> forms.
  effect: |
```
